
POST http://localhost:8080/exams/
content-type: application/json

{
    "name": "C perusteet",
    "published": "true"
}

###

PUT http://localhost:8080/exams/2
content-type: application/json

{
    "name": "Tietokantojen perusteet",
    "published": "true"
}

###

POST http://localhost:8080/exams/1/questions
content-type: application/json

{
    "text": "Miten kirjoitetaan monen rivin kommentti?"
}

###

PUT http://localhost:8080/questions/1
content-type: application/json

{
    "text": "Miten kirjoitetaan monen rivin kommentti?"
}

###

POST http://localhost:8080/questions/10o/answeroptions
content-type: application/json

{
    "text": " /* kommentti */ ",
    "correct": "true"
}

###

PUT http://localhost:8080/answeroptions/140
content-type: application/json

{
    "text": " /// kommentti /// ",
    "correct": "false"
}

###

POST http://localhost:8080/takenexams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNyIsImVtYWlsIjoiYWRtaW5FbWFpbCIsImlhdCI6MTY2OTE1MzU5NSwiZXhwIjoxNjY5MTU3MTk1fQ.axb90jD313sZGOUxm-d5eDDC3TkRjdCCde3vsZhCW38


{
    "examId": 1,
    "accountId": 27
}

###

PUT http://localhost:8080/takenexams/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNyIsImVtYWlsIjoiYWRtaW5FbWFpbCIsImlhdCI6MTY2OTE1NzIzNCwiZXhwIjoxNjY5MTYwODM0fQ.VvUOVpUSwfOMdLQX6dl9RhE0De-caP3V6u6mFtmHm_o

{
    "points": 100
}

###

POST http://localhost:8080/takenexams/2/answers
Content-Type: application/json

{
    "answerOptionId": 4
}

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "kayttaja0",
    "password": "salasana0",
    "name": "kayttajannimi",
    "isAdmin": false
}

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
    "username": "uusinimi",
    "password": "uusisalasana",
    "name": "uusi kayttajan nimi"
}

### 

POST http://localhost:8080/users/
Content-Type: application/json

{
    "email": "adminEmail",
    "password": "salasana"
}

### 

POST http://localhost:8080/login/
Content-Type: application/json

{
    "email": "sposti",
    "password": "salasana"
}

### 

POST http://localhost:8080/login/
Content-Type: application/json

{
    "email": "adminEmail",
    "password": "salasana"
}

### 
POST http://localhost:8080/exams/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNyIsImVtYWlsIjoiYWRtaW5FbWFpbCIsImlhdCI6MTY2OTAzNTkyNywiZXhwIjoxNjY5MDM5NTI3fQ.RE6v3ZnAXNh2RsAEP1q5FWUC_7oakskneXO4oED1wgk

{
    "name": "C perusteet",
    "published": "true"
}




